{
  imports = [
    ../pc
    ../daw
    ../obs
    #../wine
    ../require
    ../gaming
    ../stylix
    ../discord
    ../spotify
    ../firefox
    ../qutebrowser
    ../extra-programs/gimp.nix
    ../extra-programs/thunar.nix
    ../extra-programs/krita.nix
    ../extra-programs/spotify-player.nix
    ../extra-programs/mpv.nix
    ../extra-programs/zathura.nix
    ../extra-programs/kdenlive.nix
  ];
}
