{
  imports = [
    ../pc
    ../daw
    ../obs
    ../wine
    ../steam
    ../require
    ../gaming
    ../stylix
    ../discord
    ../firefox
    ../extra-programs/gimp.nix
    ../extra-programs/thunar.nix
    ../extra-programs/krita.nix
    ../extra-programs/spotify.nix
    ../extra-programs/spotify-player.nix
    ../extra-programs/mpv.nix
    ../extra-programs/zathura.nix
    ../extra-programs/kdenlive.nix
  ];
}
