{ pkgs, lib, inputs, ... }: let
  mkServerProperties = _config: rec {
    mkAttrs = overrides: serverProperties.default // overrides;
    serverProperties = {
      vanilla = { };
      default = {
        accepts-transfers = false;
        allow-flight = false;
        allow-nether = false;
        broadcast-console-to-ops = true;
        broadcast-rcon-to-ops = true;
        difficulty = "normal";
        enable-command-block = false;
        enable-jmx-monitoring = false;
        enable-query = false;
        enable-rcon = true;
        enable-status = true;
        enforce-secure-profile = true;
        enforce-whitelist = false;
        entity-broadcast-range-percentage = 100;
        force-gamemode = true;
        function-permission-level = 2;
        gamemode = "creative";
        generate-structures = true;
        generator-settings= { };
        hardcore = false;
        hide-online-players = false;
        initial-disabled-packs = { };
        initial-enabled-packs = "vanilla";
        level-name = "unnamedworld";
        level-seed = { };
        level-type = "minecraft\:normal";
        log-ips = true;
        max-chained-neighbor-updates = 1000000;
        max-players = 20;
        max-tick-time = 60000;
        max-world-size= 29999984;
        motd = "never knows best.";
        network-compression-threshold = 256;
        online-mode = false;
        op-permission-level = 4;
        player-idle-timeout = 0;
        prevent-proxy-connections = false;
        pvp = true;
        query.port = 25565;
        rate-limit = 0;
        #rcon.password =
        rcon.port = 25575;
        region-file-compression = "deflate";
        require-resource-pack = false;
        #resource-pack=
        #resource-pack-id=
        #resource-pack-prompt=
        #resource-pack-sha1=
        server-ip = "";
        server-port = 25565;
        simulation-distance = 4;
        spawn-animals = false;
        spawn-monsters = false;
        spawn-npcs = false;
        spawn-protection = 0;
        sync-chunk-writes = true;
        text-filtering-config = "";
        use-native-transport = true;
        view-distance = 10;
        white-list = false;

        #use a regex
        enable-jmx-monitoring=false
        rcon.port=25575
        level-seed=
        gamemode=survival
        enable-command-block=false
        enable-query=false
        generator-settings={}
        enforce-secure-profile=true
        level-name=world
        motd=A Minecraft Server
        query.port=25565
        pvp=true
        generate-structures=true
        max-chained-neighbor-updates=1000000
        difficulty=easy
        network-compression-threshold=256
        max-tick-time=60000
        require-resource-pack=false
        use-native-transport=true
        max-players=20
        online-mode=true
        enable-status=true
        allow-flight=false
        initial-disabled-packs=
        broadcast-rcon-to-ops=true
        view-distance=10
        server-ip=
        resource-pack-prompt=
        allow-nether=true
        server-port=25565
        enable-rcon=false
        sync-chunk-writes=true
        op-permission-level=4
        prevent-proxy-connections=false
        hide-online-players=false
        resource-pack=
        entity-broadcast-range-percentage=100
        simulation-distance=10
        rcon.password=
        player-idle-timeout=0
        force-gamemode=false
        rate-limit=0
        hardcore=false
        white-list=false
        broadcast-console-to-ops=true
        spawn-npcs=true
        spawn-animals=true
        log-ips=true
        function-permission-level=2
        initial-enabled-packs=vanilla
        level-type=minecraft\:normal
        text-filtering-config=
        spawn-monsters=true
        enforce-whitelist=false
        spawn-protection=16
        resource-pack-sha1=
        max-world-size=29999984
    };
  };
}
