{
  serverProperties = {
    accepts-transfers = false;
    allow-flight = false;
    allow-nether = false;
    broadcast-console-to-ops = true;
    broadcast-rcon-to-ops = true;
    difficulty = "normal";
    enable-command-block = false;
    enable-jmx-monitoring = false;
    enable-query = false;
    enable-rcon = true;
    enable-status = true;
    enforce-secure-profile = true;
    enforce-whitelist = false;
    entity-broadcast-range-percentage = 100;
    force-gamemode = true;
    function-permission-level = 2;
    gamemode = "creative";
    generate-structures = true;
    generator-settings= { };
    hardcore = false;
    hide-online-players = false;
    initial-disabled-packs = { };
    initial-enabled-packs = "vanilla";
    level-name = "unnamedworld";
    level-seed = { };
    level-type = "minecraft\:normal";
    log-ips = true;
    max-chained-neighbor-updates = 1000000;
    max-players = 20;
    max-tick-time = 60000;
    max-world-size= 29999984;
    motd = "never knows best.";
    network-compression-threshold = 256;
    online-mode = false;
    op-permission-level = 4;
    player-idle-timeout = 0;
    prevent-proxy-connections = false;
    pvp = true;
    query.port = 25565;
    rate-limit = 0;
    #rcon.password =
    rcon.port = 25575;
    region-file-compression = "deflate";
    require-resource-pack = false;
    #resource-pack=
    #resource-pack-id=
    #resource-pack-prompt=
    #resource-pack-sha1=
    server-ip = "";
    server-port = 25565;
    simulation-distance = 4;
    spawn-animals = false;
    spawn-monsters = false;
    spawn-npcs = false;
    spawn-protection = 0;
    sync-chunk-writes = true;
    text-filtering-config = "";
    use-native-transport = true;
    view-distance = 10;
    white-list = false;
  };
}
